In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv("planets.csv", skiprows=34)

In [10]:
data.head()

,loc_rowid,pl_hostname,pl_letter,pl_name,pl_discmethod,pl_pnum,pl_orbper,pl_orbsmax,pl_orbeccen,pl_orbincl,...,dec,st_dist,st_optmag,st_optband,gaia_gmag,st_teff,st_mass,st_rad,rowupdate,pl_facility
0,1,11 Com,b,11 Com b,Radial Velocity,1,326.03000,1.29,0.231,NaN,...,17.792868,93.37,4.740,V (Johnson),4.372,4742.0,2.70,19.00,2014-05-14,Xinglong Station
1,2,11 UMi,b,11 UMi b,Radial Velocity,1,516.21997,1.53,0.080,NaN,...,71.823898,125.72,5.016,V (Johnson),4.500,4213.0,2.78,29.79,2018-09-06,Thueringer Landessternwarte Tautenburg
2,3,14 And,b,14 And b,Radial Velocity,1,185.84000,0.83,0.000,NaN,...,39.236198,75.59,5.227,V (Johnson),4.872,4813.0,2.20,11.00,2014-05-14,Okayama Astrophysical Observatory
3,4,14 Her,b,14 Her b,Radial Velocity,1,1773.40002,2.93,0.370,NaN,...,43.817646,17.94,6.610,V (Johnson),6.379,5338.0,0.90,0.93,2018-09-06,W. M. Keck Observatory
4,5,16 Cyg B,b,16 Cyg B b,Radial Velocity,1,798.50000,1.66,0.680,NaN,...,50.517525,21.41,6.250,V (Johnson),6.057,5750.0,1.08,1.13,2018-09-06,Multiple Observatories

In [12]:
data.describe()

,loc_rowid,pl_pnum,pl_orbper,pl_orbsmax,pl_orbeccen,pl_orbincl,pl_bmassj,pl_radj,pl_dens,pl_ttvflag,...,pl_k2flag,pl_nnotes,ra,dec,st_dist,st_optmag,gaia_gmag,st_teff,st_mass,st_rad
count,3826.000000,3826.000000,3.732000e+03,2173.000000,1203.000000,707.000000,1416.000000,3022.000000,389.000000,3826.000000,...,3826.000000,3826.000000,3826.000000,3826.000000,3813.000000,3685.000000,3693.000000,3670.000000,3052.000000,3568.000000
mean,1913.500000,1.772608,2.387994e+03,6.953685,0.168452,86.119272,2.609544,0.361643,2.489962,0.061945,...,0.098275,0.649765,249.011848,25.759116,622.991513,12.796136,12.695264,5495.175779,1.016576,1.551698
std,1104.615393,1.166882,1.198758e+05,83.977130,0.194047,7.984802,4.521466,0.415049,5.238963,0.241086,...,0.297725,0.517582,83.213441,30.936204,745.699879,2.930133,2.961830,1688.028865,0.669570,3.793141
min,1.000000,1.000000,9.070629e-02,0.004400,0.000000,7.700000,0.000060,0.030000,0.030000,0.000000,...,0.000000,0.000000,0.325750,-84.231613,1.290000,0.850000,2.804000,575.000000,0.020000,0.040000
25%,957.250000,1.000000,4.580151e+00,0.058000,0.016850,86.085000,0.161500,0.139000,0.410000,0.000000,...,0.000000,0.000000,238.234034,7.353343,177.000000,11.700000,11.535000,5048.250000,0.817500,0.800000
50%,1913.500000,1.000000,1.190533e+01,0.119000,0.101000,88.043000,0.937000,0.206000,0.980000,0.000000,...,0.000000,1.000000,288.098254,41.339339,500.000000,13.764000,13.689000,5600.000000,0.970000,0.970000
75%,2869.750000,2.000000,4.180677e+01,0.689000,0.250000,89.250000,2.690000,0.304000,2.500000,0.000000,...,0.000000,1.000000,294.027577,46.039860,864.310000,14.955000,14.912000,5923.000000,1.130000,1.240000
max,3826.000000,8.000000,7.300000e+06,2500.000000,0.970000,90.760000,55.590000,6.900000,77.700000,1.000000,...,1.000000,3.000000,359.974304,85.736153,8500.000000,20.150000,20.480000,57000.000000,23.560000,71.230000

In [14]:
data.isnull().sum(axis = 0)

loc_rowid           0
pl_hostname         0
pl_letter           0
pl_name             0
pl_discmethod       0
pl_pnum             0
pl_orbper          94
pl_orbsmax       1653
pl_orbeccen      2623
pl_orbincl       3119
pl_bmassj        2410
pl_bmassprov     2410
pl_radj           804
pl_dens          3437
pl_ttvflag          0
pl_kepflag          0
pl_k2flag           0
pl_nnotes           0
ra_str              0
ra                  0
dec_str             0
dec                 0
st_dist            13
st_optmag         141
st_optband        141
gaia_gmag         133
st_teff           156
st_mass           774
st_rad            258
rowupdate           0
pl_facility         0
dtype: int64

In [ ]:
plt.hist(data['pl_discmethod'])

In [ ]:
sns.dist(data['st_mass'])

In [ ]:
dir(data['st_mass'])